name: Build App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.19.0]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change to app directory
        run: cd app

      - name: Install dependencies
        run: yarn install

      - name: Build the app
        run: yarn build

      - name: Move the build output to /docs
        run: mv build ../docs
